Verbetes = [
    'Tubarao', 'Animal Aquático',
    'Fedida', 'Adjetivo que a Rafa possui',
    'Maratona', 'É a corrida mais longa do atletismo',
    'Especial', 'Aquele que é único',
    'Divorciado', 'Se separou judicialmente do cônjuge',
    'Flauta', 'Instrumento de sopro',
    'Estado', 'Divisão territorial',
    'Agulha', 'Ferramenta pequena para perfurar',
    'Enigma', 'Algo incompreensíevl ou ambíguo',
    'Sorvete', 'Creme congelado, doce e aromatizado, feito geralmente de água, leite ou suco de frutas.',
    'Aranha', 'Animal articulado, de oito patas e sem asas, da classe dos arácnidos.',
    'Feio', 'Quem ou o que tem aspecto considerado desagradável.',
    'Bebida', 'Vinho ou outro líquido alcoólico, próprio para se beber.',
    'Filha', 'Pessoa do sexo feminino em relação aos progenitores.',
    'Ferro', 'Elemento químico de número atômico 26, que corresponde a um corpo simples, metal dúctil, maleável e muito tenaz, de cor cinzenta azulada e muito útil na indústria e nas artes.',
    'Rosto', 'Conjunto da testa, olhos, nariz, boca, mento e faces das pessoas ou suas representações.',
    'Coruja', 'Ave de rapina noturna.',
    'Cabra', 'Designação dada a vários mamíferos ruminantes da família dos bovídeos.',
    'Chave', 'Instrumento com que se faz correr a lingueta de uma fechadura para a abrir ou fechar.',
    'Filmes', 'Tira plástica revestida com uma emulsão sensível à luz, e na qual se registram as imagens em fotografia e em cinematografia.',
    'Pai', 'Aquele que tem um ou mais filhos.',
    'Leite', 'Líquido secretado pelas tetas das fêmeas dos mamíferos.',
    'Verde', 'Que é de uma cor produzida pela combinação do amarelo com o azul, muito espalhada no reino vegetal.',
    'Alface', 'Planta asterácea hortense, muito usada na alimentação humana, sobretudo em saladas.',
    'Corrida', 'Ato de correr.',
    'Mochila', 'Saco com alças ou correias para ser pendurado nos ombros, usado geralmente para transportar às costas roupas, provisões ou outros objetos.',
    'Cometa', 'Astro que gira em volta do Sol, descrevendo órbita muito excêntrica e que consiste geralmente num ponto brilhante (núcleo), envolvido por uma nebulosidade (cabeleira), com um rastro luminoso (cauda).',
    'Riso', 'Ato ou efeito de rir.',
    'Nuvem', 'Conjunto de pequenas partículas de água suspensas na atmosfera, que pode originar chuva ou neve.',
    'Soldado', 'Que se soldou.',
    'Rio', 'Grande curso de água natural, quase sempre oriunda das montanhas, que recebe no trajeto águas de regatos e ribeiros, e desagua em outro curso de água, num lago ou no mar.',
    'Cabine', 'Pequeno compartimento nos navios mercantes.',
    'Copo', 'Recipiente cilíndrico e sem asas, usado para beber.',
    'Coelho', 'Designação dada a diversos mamíferos lagomorfos da família dos leporídeos, muito prolíferos, de cauda curta, orelhas e patas longas.',
    'Ombro', 'Cada uma das duas partes do tronco humano onde o braço se une às costas, junto à clavícula e à escápula.',
    'Mochila', 'Saco com alças ou correias para ser pendurado nos ombros, usado geralmente para transportar às costas roupas, provisões ou outros objetos.',
    'Chave', 'Instrumento com que se faz correr a lingueta de uma fechadura para a abrir ou fechar.',
    'Parafuso', 'Peça cilíndrica canelada em espiral, destinada a apertar ou prender duas ou mais peças ou superfícies.',
    'Chocolate', 'Produto alimentício, de coloração castanha, obtido a partir de cacau torrado moído e açúcar.',
    'Vaca', 'Fêmea do boi.',
    'Morango', 'O fruto do morangueiro.',
    'Chuva', 'Água que cai das nuvens.',
    'Rato', 'Roedor que causa espanto',
    'Lento', 'Antônimo de Veloz.',
    'Novo', 'Feito recentemente ou que existe há pouco tempo.',
    'Beco', 'Rua escura, estreita e curta, e às vezes sem saída.',
    'Galeria', 'Corredor ou compartimento sobre o comprido, geralmente com janelas ou cobertura envidraçada.',
    'Torpedo', 'Engenho automotor submarino, carregado de explosivo, utilizado contra alvos marítimos por navios ou aeronaves.',
    'Internacional', 'Que é comum ou respeita a duas ou mais nações.',
    'Oculista', 'Especialista de doenças dos olhos.',
    'Lança', 'Arma ofensiva formada por uma haste que tem na extremidade um ferro pontiagudo.',
    'Zarabatana', 'Tubo comprido pelo qual se impelem com o sopro pequenos projéteis como pequenas pedras, setas, etc.'
    ]